baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Ivano D’Apice'
theme = ["hugo-embed-pdf-shortcode", "typo"]

[params]
theme = 'dark'
colorPalette = 'gruvebox'
showFooter = true
footerContent = "Your **custom** md `footer`"
singleDateFormat = '2 January 2006'

[params.giscus]
enable = true
repo="ivanodapice/ivanodapice.github.io"
repoid="MDEwOlJlcG9zaXRvcnk0MDQ2MTAzNjY="
category="General"
categoryid="DIC_kwDOGB3dPs4CjGfo"
mapping="url"
strict="0"
reactionsenabled="1"
emitmetadata="0"
inputposition="bottom"
theme="preferred_color_scheme"
crossorigin="anonymous"

[markup]
[markup.highlight]
style = 'algol'

[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "appunti"
url = "/appunti"

[permalinks]
  appunti = '/appunti/:slug'