baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Ivano D’Apice'
theme = ["hugo-embed-pdf-shortcode", "typo"]
pluralizeListTitles = "false"

[params]
theme = 'light'
colorPalette = 'catpuccin'
showFooter = true
footerContent = "All content licensed under CC BY-SA 4.0 license unless otherwise stated. Copyright © 2024 **Ivano D’Apice**."
singleDateFormat = '2 January 2006'
paginationSize = 100
homeIntroTitle = 'Benvenuti nel mio sito web.'
homeIntroContent = """
Se per qualsiasi ragione ci fosse bisogno di contattarmi, sotto ci sono le mie pagine.
"""

[params.giscus]
enable = true
repo="ivanodapice/ivanodapice.github.io"
repoid="MDEwOlJlcG9zaXRvcnk0MDQ2MTAzNjY="
category="General"
categoryid="DIC_kwDOGB3dPs4CjGfo"
mapping="url"
strict="0"
reactionsenabled="1"
emitmetadata="0"
inputposition="bottom"
theme="preferred_color_scheme"
crossorigin="anonymous"

[markup]
[markup.highlight]
style = 'algol'

[[params.social]]
name = "linkedin"
url = "https://it.linkedin.com/in/ivanodapice"

[[params.social]]
name = "github"
url = "https://github.com/ivanodapice"

[[params.social]]
name = "telegram"
url = "https://t.me/sonoivano"

[[params.social]]
    name = "email"
    url  = "mailto:ivanodapice@hotmail.com"

[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "appunti"
url = "/appunti"

[[params.menu]]
name = "progetti"
url = "/progetti"

[permalinks]
  appunti = '/appunti/:slug'
  progetti = '/progetti/:slug'